name: Build Wheels

on:  
  push:
    tags:
      - '*'
env:
  CIBW_SKIP: pp* *-musllinux* *i686

jobs:
  build_wheels:
    name: Build wheels on ${{matrix.arch}} for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019, macos-latest]
        arch: [auto]
        include:
          - os: ubuntu-latest
            arch: aarch64

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        if:  ${{ matrix.arch == 'aarch64' }}
        uses: docker/setup-qemu-action@v1

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        # to supply options, put them in 'env', like:
        env:
          CIBW_ARCHS_LINUX: ${{matrix.arch}}
          CIBW_BEFORE_BUILD: pip install numpy setuptools wheel pkginfo packaging twine
          CIBW_ARCHS_MACOS: "x86_64 arm64"

      - name: Upload built wheels
        uses: actions/upload-artifact@v4
        with:
          name: built-wheels-${{ matrix.os }}-${{ matrix.arch }}
          path: ./wheelhouse/*.whl
          if-no-files-found: warn
